spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cars
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

  h2:
    console:
      enabled: true
      path: /h2-console

server:
  error:
    include-message: always
